# Generated by Django 5.2.5 on 2025-08-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoaplicacion',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
