# Generated by Django 5.2.5 on 2025-08-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0002_pagoaplicacion_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('aporte', 'Aporte'), ('prestamo', 'Préstamo')], default='aporte', max_length=20),
        ),
    ]
