# Generated by Django 5.2.5 on 2025-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0004_remove_pago_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaprestamo',
            name='capital_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='interes_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pago',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='pagos/soportes/'),
        ),
    ]
