# Generated by Django 5.2.5 on 2025-08-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0005_cuotaprestamo_capital_pagado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoaplicacion',
            name='cuota_pagada',
        ),
        migrations.RemoveField(
            model_name='pagoaplicacion',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pagoaplicacion',
            name='aporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones', to='fonar.aporte'),
        ),
        migrations.AlterField(
            model_name='pagoaplicacion',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fonar.cuotaprestamo'),
        ),
        migrations.AlterField(
            model_name='pagoaplicacion',
            name='monto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
