# Generated by Django 5.2.5 on 2025-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0006_remove_pagoaplicacion_cuota_pagada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoaplicacion',
            name='fecha_aporte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
