# Generated by Django 5.2.5 on 2025-08-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0007_pagoaplicacion_fecha_aporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuotaprestamo',
            name='saldo',
        ),
    ]
