# Generated by Django 5.2.5 on 2025-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0008_remove_cuotaprestamo_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
