# Generated by Django 5.2.5 on 2025-08-28 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0009_alter_pago_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
