# Generated by Django 5.2.5 on 2025-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0010_alter_pago_fecha'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuotaprestamo',
            constraint=models.UniqueConstraint(fields=('prestamo', 'numero'), name='uq_prestamo_numero'),
        ),
    ]
