# Generated by Django 5.2.5 on 2025-09-01 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0011_cuotaprestamo_uq_prestamo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('asociado', 'Asociado'), ('tercero', 'Tercero')], max_length=20)),
                ('tipo_credito', models.CharField(default='consumo', max_length=50)),
                ('cuotas_min', models.PositiveIntegerField()),
                ('cuotas_max', models.PositiveIntegerField()),
                ('interes_mensual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('asociado', 'Asociado'), ('tercero', 'Tercero')], default='asociado', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_deseada_desembolso', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
