# Generated by Django 5.2.5 on 2025-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonar', '0012_tasainteres_usuario_tipo_usuario_solicitudprestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(unique=True)),
                ('nequi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daviplata', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
